

###
GET http://localhost:3001/api/people

###

GET http://localhost:3001/api/info

###

DELETE http://localhost:3001/api/persons/1

###

POST localhost:3001/api/people
Content-Type: application/json

{
  "name": "Jacob Peralta",
  "number": "885-511-6869"
}


