

###
GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/info

###

DELETE http://localhost:3001/api/persons/1

###

POST localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Jacob Atienza",
  "number": "885-511-6869"
}


